### ISSUE TITLE
Drop-in replacement for "delete-empty-up"

### ISSUE THREAD

**Issue by OMasroor** [ozum/rm-up#1]
Hi ozum,

I was using your one-of-a-kind **delete-empty-up** package before it got deprecated. 

I tried replacing it with rm-up simply by changing `import deleteEmptyUp from 'delete-empty-up'` to `import rmUp from 'rm-up'`

and `await deleteEmptyUp(absolutePathToFile)` to `await rmUp(absolutePathToFile, { relative: false, deleteInitial: true })`

but it no longer deletes the file. If I print the return value using `verbose: true`, it only returns an empty array. Also, there is no error thrown.

Do you have any information on what's causing this?

**Comment by ozum** [comment]
Sorry for the inconvenience, could you please list a simple tree structure that is not deleted.

You can post here as a list. For example:

```
|- a
   |- some.txt
|- b
   | b1
```

**Comment by OMasroor** [comment]
Never mind, I believe I've found the issue.

This works for files but not for directories:

`await rmUp('C:\\Users\\OMasroor\\FileToDelete.txt', { relative: false, deleteInitial: true }) // This works.`

`await rmUp('C:\\Users\\OMasroor\\DirectoryToDelete\\', { relative: false, deleteInitial: true }) // This does not work.`

`await rmUp('C:\\Users\\OMasroor\\DirectoryToDelete', { relative: false, deleteInitial: true }) // This does not work.`

If I add `cwd: 'C:\\'`, then it works for both files and directories:

`await rmUp('C:\\Users\\OMasroor\\FileToDelete.txt', { cwd: 'C:\\', relative: false, deleteInitial: true }) // This works.`

`await rmUp('C:\\Users\\OMasroor\\DirectoryToDelete\\', { cwd: 'C:\\', relative: false, deleteInitial: true }) // This works.`

`await rmUp('C:\\Users\\OMasroor\\DirectoryToDelete', { cwd: 'C:\\', relative: false, deleteInitial: true }) // This works.`

**Comment by ozum** [comment]
@OMasroor, could you please check what is actual cwd while this command is executed:

`await rmUp('C:\\Users\\OMasroor\\DirectoryToDelete', { relative: false, deleteInitial: true }) // This does not work.`

**Comment by ozum** [comment]
I found the reason. For a safety measure, `rm-up` only deletes paths below `options.stop` which is by default equals to the `cwd`.

So to delete you have several options;

1. Paths should below `options.stop`: `await rmUp('C:\\Users\\OMasroor\\DirectoryToDelete\\', { relative: false, deleteInitial: true, stop: 'C:\\Users\\OMasroor' })`
2. If no `stop` is provided, paths should below `cwd`, because `options.stop` is equals `cwd` by default. e.g. `await rmUp('C:\\Users\\OMasroor\\DirectoryToDelete\\', { relative: false, deleteInitial: true, cwd: 'C:\\Users\\OMasroor' })`
3. If no `options.stop` or `options.cwd` provided, paths should below actual `cwd`.

```ts
process.chdir('C:\\Users\\OMasroor'); // You may not need this, if cwd is already equals to your desired value.
await rmUp('C:\\Users\\OMasroor\\DirectoryToDelete\\', { relative: false, deleteInitial: true })
```

I will add this explanation `README.md`, because other users may need this detail too.

**Comment by OMasroor** [comment]
Thank you for the help!

However, I'm just curious why this was working for files but not for directories:

`await rmUp('C:\\Users\\OMasroor\\FileToDelete.txt', { relative: false, deleteInitial: true }) // This works.`

Does the safety only apply to directories but not to files? Or is it a bug?

**Comment by ozum** [comment]
Hmm. I missed that point. I'll check and respond accordingly.

**Comment by ozum** [comment]
The file is not deleted during my tests.

Could you please add `console.log(process.cwd())` just before the lines:

`await rmUp('C:\\Users\\OMasroor\\FileToDelete.txt', { relative: false, deleteInitial: true }) // This works.`

`await rmUp('C:\\Users\\OMasroor\\DirectoryToDelete', { relative: false, deleteInitial: true }) // This does not work.`

So we can see cwd.

**Comment by OMasroor** [comment]
Here are my findings:

This works:

```
// process.cwd():   C:\\Users\\OMasroor\\Desktop\\my-package
// absolutePath:    C:\\MyDirectory\\FileToDelete.txt

await rmUp(absolutePath, { deleteInitial: true, relative: false })
```

This doesn't work and doesn't throw an error:

```
// process.cwd():   C:\\Users\\OMasroor\\Desktop\\my-package
// absolutePath:    C:\\Users\\OMasroor\\MyDirectory\\FileToDelete.txt

await rmUp(absolutePath, { deleteInitial: true, relative: false })
```

**Comment by ozum** [comment]
I made two changes:

1. `rmUp` does not delete the initial file if it is not under stop dir.
2. default stop path does not have any default value from now on. So by default, every `rmUp` command deletes if directories are empty. It seems a good idea to assign the stop path to the cwd at first, but it really confuses users, because if the cwd is different than the path to be removed, nothing happens.

In macOS it seems OK. Could you please test below:

This should not delete:

``` 
// process.cwd():   C:\\Users\\OMasroor\\Desktop\\my-package
// absolutePath:    C:\\MyDirectory\\FileToDelete.txt

await rmUp(absolutePath, { deleteInitial: true, relative: false, stop: "C:\\Users\\OMasroor\\Desktop\\my-package" })
```

This should not delete:

``` 
// process.cwd():   C:\\Users\\OMasroor\\Desktop\\my-package
// absolutePath:    C:\\MyDirectory\\FileToDelete.txt

await rmUp(absolutePath, { deleteInitial: true, relative: false, stop: "C:\\Users\\OMasroor\\Desktop\\my-package" })
```

This should delete:

``` 
// process.cwd():   C:\\Users\\OMasroor\\Desktop\\my-package
// absolutePath:    C:\\MyDirectory\\FileToDelete.txt

await rmUp(absolutePath, { deleteInitial: true, relative: false })
```

This should delete:

``` 
// process.cwd():   C:\\Users\\OMasroor\\Desktop\\my-package
// absolutePath:    C:\\MyDirectory\\FileToDelete.txt

await rmUp(absolutePath, { deleteInitial: true, relative: false })
```

**Comment by OMasroor** [comment]
I tried to test it with rm-up 1.0.4 but now webpack is unable to compile rm-up:

```
PS C:\Users\OMasroor\Desktop\my-package> yarn electron:serve
yarn run v1.22.10
$ vue-cli-service electron:serve
 INFO  Starting development server...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                          14:49:17
 error  in ./node_modules/rm-up/dist/scanner.js

Module parse failed: Unexpected token (92:67)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     async readDirUp(path, isInitial = true) {
|         /* istanbul ignore next */
>         const isAdded = __classPrivateFieldGet(this, _index)[path]?.status === STATUS.PROCESSING || __classPrivateFieldGet(this, _index)[path]?.status === STATUS.READY;
|         if (isAdded || !this.belowStop(path))
|             return;

 @ ./node_modules/rm-up/dist/main.js 9:34-54
 @ ./node_modules/rm-up/dist/index.js
 @ ./src/utils/remove-leftover-temp-directories.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.200.122:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

This wasn't happening with rm-up 1.0.0.

**Comment by ozum** [comment]
I guess, it is because of `?.`

I don't use webpack, but there is a blog how to use `?.` with webpack: https://medium.com/@danwild.io/optional-chaining-for-javascript-with-babel-7-and-webpack-4-2de8fd9dbdd5

**Comment by OMasroor** [comment]
Thank you for the tip. I got 1.0.4 working and tested it. It is working correctly.

Results:

```js
Windows:

// process.cwd(): C:\Users\OMasroor\Desktop\my-package
// shouldBeDeleted: C:\Users\OMasroor\Documents\Test\shouldBeDeleted.txt

await rmUp(shouldBeDeleted, { deleteInitial: true, relative: false }) //This works.

// process.cwd(): C:\Users\OMasroor\Desktop\my-package
// shouldNotBeDeleted: C:\Users\OMasroor\Documents\Test\shouldNotBeDeleted.txt

await rmUp(shouldNotBeDeleted, { deleteInitial: true, relative: false, stop: process.cwd() }) // Doesn't work and doesn't throw an error.



macOS:

// process.cwd(): /Users/OMasroor/Desktop/my-package
// shouldBeDeleted: /Users/OMasroor/Documents/Test/shouldBeDeleted.txt

await rmUp(shouldBeDeleted, { deleteInitial: true, relative: false }) //This works.

// process.cwd(): /Users/OMasroor/Desktop/my-package
// shouldNotBeDeleted: /Users/OMasroor/Documents/Test/shouldNotBeDeleted.txt

await rmUp(shouldNotBeDeleted, { deleteInitial: true, relative: false, stop: process.cwd() }) // Doesn't work and doesn't throw an error.



Ubuntu:

// process.cwd(): /home/OMasroor/Desktop/my-package
// shouldBeDeleted: /home/OMasroor/Documents/Test/shouldBeDeleted.txt

await rmUp(shouldBeDeleted, { deleteInitial: true, relative: false }) // This works.

// process.cwd(): /home/OMasroor/Desktop/my-package
// shouldNotBeDeleted: /home/OMasroor/Documents/Test/shouldNotBeDeleted.txt

await rmUp(shouldNotBeDeleted, { deleteInitial: true, relative: false, stop: process.cwd() }) // Doesn't work and doesn't throw an error.
```

Thank you for your work.

**Comment by ozum** [comment]
@OMasroor also thank you for helping me to fix this bug.
