### ISSUE TITLE
`rmUp is not a function` after migrating to native ESM modules

### ISSUE THREAD

**Issue by kachkaev** [ozum/rm-up#2]
👋 @ozum! Thanks a lot for this small but rather handy lib!

I’ve been using `rm-up` in [a side project](https://github.com/kachkaev/tooling-for-how-old-is-this-house) for a few months. My code is written in TypeScript and I have been transpiling it to CommonJS using `ts-node`. No issues with TypeScript checks or runtime for all this time 👍

Earlier today I [dropped](https://github.com/kachkaev/tooling-for-how-old-is-this-house/commit/cddc7beb381f4ff3264e05568f92057fe24ec330) ESM-to-CommonJS transpilation. Oddly enough, `rm-up` stopped working for me in runtime. Here is an MWE:

```ts
// path/to/script.ts
import rmUp from "rm-up";

await rmUp("some-path");
```

This gives me no `tsc` linting errors, but the code does not work.

```
TypeError: rmUp is not a function
```

Here is a working [hotfix](https://github.com/kachkaev/tooling-for-how-old-is-this-house/commit/aa14039f05c88d88a93964493cebfdd6168cc0a4):

```diff
  // path/to/script.ts
  import rmUp from "rm-up";

- await rmUp("some-path");
+ // @ts-expect-error -- upstream issue with native ESM modules
+ await rmUp.default("some-path");
```

And here is how I call the script:

```bash
yarn exe path/to/script.ts
```

```json
{
  "type": "module",
  "scripts": {
    "exe": "node --loader ts-node/esm/transpile-only --experimental-specifier-resolution=node"
  },
  "dependencies": {
    "rm-up": "1.0.4",
    "ts-node": "10.4.0"
  }
}
```

I am not an expert in all this ESM vs CommonJS business, but am happy to help you with further investigation and testing if needed. In the meantime, if you have any thoughts or questions, feel free to share!

**Comment by ozum** [comment]
Hi @kachkaev, `rm-up` is written as a CommonJS module.

**Comment by kachkaev** [comment]
Yeah clearly there’s something going on at the boundary of CommonJS and ESM. The thing is that I’m using other CommonJS packages like `lodash` from my ESM files and there are no issues there. AFAIU, Importing CommonJS from ESM is supported, while the reverse is not.

What I find strange is the usage of `__esModule` in [`rm-up/dist/index.js`](https://unpkg.com/browse/rm-up@1.0.4/dist/index.js). An ‘honest’ default export from CommonJS would be `exports = something` rather than `exports.default = something`. This is probably where that extra `.default` is coming from on my end.

Check out `lodash` for comparison: [`index.js`](https://unpkg.com/browse/lodash@4.17.21/index.js) → [`lodash.js`](https://unpkg.com/browse/lodash@4.17.21/lodash.js) (no `__esModule` or `.default`).

**Comment by kachkaev** [comment]
Default exports are a common source of many issues. It’s not just about ESM/CommonJS, but also variable naming, refactoring and so on. There are a bunch of articles suggesting to stop using `export default` for a few good reasons. Some examples:

- https://basarat.gitbook.io/typescript/main-1/defaultisbad
- https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad
- https://ilikekillnerds.com/2019/08/default-exports-bad/

Perhaps, `rm-up` could deprecate `import rmUp from "rm-up"` in favour of `import { rmUp } from "rm-up"`? No breaking changes are necessary, so this can be released as `1.1.0` 🤔

I’ve seen a few packages maintainers switching to named exports recently. [Here’s `execa`](https://github.com/sindresorhus/execa/releases/tag/v6.0.0) as the first thing that has come to my mind.

**Comment by ozum** [comment]
There is some debate about default vs named export. Both parties have some arguments. TBH, I'm neutral.

Could you first please verify, having a named export solves your problem by following steps below:

1. Download this repository in an empty folder.
2. Add `export { rmUp };` to `src/index.ts` file.
3. Build the library: `npm install && npm run build`
4. Copy newly created `dist` folder over the original `node_modules/rm-up/dist` folder in your project.
5. Verify it is working.

I can add the named export if it fixes your problem. I can keep both default and named export at the same time to preserve backward compatibility.

**Comment by kachkaev** [comment]
Yep, it works for me! See #3

<img width="1166" alt="Screenshot 2021-12-31 at 12 44 19" src="https://user-images.githubusercontent.com/608862/147824638-50f39784-09e0-4b66-90fc-5dd534a50f3e.png">

```
yarn exe src/scripts/rm-up-test
```
```
named [AsyncFunction: rmUp]
default { rmUp: [Getter], default: [AsyncFunction: rmUp] }
```

**Comment by ozum** [comment]
@kachkaev, thanks, I merged your changes and fixed another deprecated API call from `rm`.

My build workflow has been changed since the last update. Could you verify uploaded `npm` package is working for you as expected? If not, please open another issue.

**Comment by kachkaev** [comment]
Just tried the new version in https://github.com/kachkaev/tooling-for-how-old-is-this-house/commit/389c4f2ef9128c1f05a762192a9791bb59a9cbc1. All looks good!

Thanks a lot for releasing `1.1.0` so quickly! Happy New Year! 🎉

**Comment by ozum** [comment]
Happy new year you too 🎉

**Comment by ozum** [comment]
> PS (if you haven’t seen that comment yet): #3 (comment)

Actually, you didn't forget. However `README.md` is auto-generated from `README.njk`automatically and your change has been overwritten.

I fixed it, thanks for the warning. It will be updated in the next release.
